# Configure the destination of fields type.
# NOTE : You must at least create the directories where the files will be stored.

fields:
    basic:
        path: './public/basic-fields.php'

# Define here your custom post types, menu names or taxonmies.
locations:

    Post:
        post_type:
            post: 'Articles'
            page: 'Pages'
        post_template:
        post_status:
        post_format:
        post_category:
        post_taxonomy:
        post:
    
    Page:
        page_template:
        page_type:
            front_page: 'Homepage'
        page_parent:
        page:
    
    User:
        current_user:
        current_user_role:
        user_form:
        user_role:

    Forms:
        taxonomy:
        attachment:
        comment:
        widget:
        nav_menu:
        nav_menu_item: